raw <- read.table('household_power_consumption.txt',sep=';',header=T, na.strings = '?')
raw$datetime <- strptime(paste(raw$Date, raw$Time), format='%d/%m/%Y %H:%M:%S')
part <- subset(raw, as.Date(datetime) == '2007-02-01' | as.Date(datetime) == '2007-02-02')
png(filename='plot4.png',width=480,height=480,units='px')
par(mfrow = c(2,2))
plot (part$datetime,part$Global_active_power,type="l",main = "" , xlab = "", ylab = "Global active power")
plot (part$datetime,part$Voltage,type="l",main = "" , xlab = "datetime", ylab = "Voltage")
plot (part$datetime,part$Sub_metering_1,type = "l", xlab = "", ylab = "Energy sub metering", col = "black")
lines(part$datetime, part$Sub_metering_2, col='red')
lines(part$datetime, part$Sub_metering_3, col='blue')
legend("topright", col = c("black", "red", "blue"), lty= "solid", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty='n')
plot(part$datetime,part$Global_reactive_power,type="l",main = "" , xlab = "", ylab = "Global_reactive_power")
dev.off()